import=["<string>"]

[window]
opacity = 0.8
decorations = "None"

[colors.normal]
green = "#00ff00"
yellow = "#e29d1c"

[font]
normal = { family = "Inconsolata", style = "Regular" }
size = 10.5

[cursor]
style = { shape = "Beam", blinking = "Off" }

[mouse]
hide_when_typing = true
