import=["<string>"]

[window]
opacity = 1.0
#decorations = "None"

[colors.primary]
background= "#121212"

[colors.normal]
green = "#00ff00"
yellow = "#e29d1c"

[font]
normal = { family = "Inconsolata", style = "Regular" }
size = 10

[cursor]
style = { shape = "Beam", blinking = "Off" }

[mouse]
hide_when_typing = true
